### ISSUE TITLE
npm install doesn't work

### ISSUE THREAD

**Issue by daukadolt** [ayanginet/bytes-hook-test#1]
`npm install` doesn't work

**Comment by a5net** [comment]
Please follow community guidelines when submitting an issue.

thanks!

**Comment by bytestreme** [comment]
![image](https://user-images.githubusercontent.com/44555427/98027313-b04f8200-1e36-11eb-878a-88e866e9b583.png)
Reproduced with `npm install`

**Comment by daukadolt** [comment]
I've attached a video from my desktop running into the issue

[![IScreen video](https://img.youtube.com/vi/Jb2yDCumANM/0.jpg)](https://www.youtube.com/watch?v=Jb2yDCumANM)
